import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import { getProviders, getSession, useSession } from "next-auth/react";
import { useRecoilState } from "recoil";
import Login from "../components/Login";
import { modalState, postIdState } from "../atoms/modalAtom";
import Modal from "../components/Modal";
import axios from "axios";
import Widgets from "../components/Widgets";

export default function Home({ trendingResults, followResults, providers }) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  if (!session) return <Login providers={providers} />;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex min-h-screen max-w-[1500px] bg-black">
        <Sidebar />
        <Feed />
        {isOpen && <Modal />}
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  let trendingResults;
  let followResults;
  try {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/getTrending`
    );
    trendingResults = res.data;
  } catch (err) {
    console.log(err);
  }
  try {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/getFollows`
    );
    followResults = res.data;
  } catch (err) {
    console.log(err);
  }
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      followResults,
      trendingResults,
      providers,
      session,
    },
  };
}
